ARG ELK_VERSION                                                                                                      
                                                                                                                     
FROM docker.elastic.co/elastic-agent/elastic-agent:${ELK_VERSION}                                                    
